"""add persona_sessions, messages.persona_session_id

Regular persona chat only. messages.persona_session_id and
messages.challenge_session_id are NOT mutually exclusive by constraint — a
future task wiring Brain/PersonaSession into challenges too will need both
set on the same row, so no CHECK constraint is added here to enforce
exclusivity.

Revision ID: 31d8311e0009
Revises:
Create Date: 2026-07-25 01:32:48.197722

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = '31d8311e0009'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_persona_id', sa.Integer(), nullable=False),
    sa.Column('human_persona_id', sa.Integer(), nullable=False),
    sa.Column('arousal', sa.Float(), nullable=False),
    sa.Column('patience', sa.Float(), nullable=False),
    sa.Column('mood', sa.Float(), nullable=False),
    sa.Column('rapport', sa.Float(), nullable=False),
    sa.Column('curiosity', sa.Float(), nullable=False),
    sa.Column('last_subject', sa.String(), nullable=True),
    sa.Column('topic_repeat_streak', sa.Integer(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('block_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ai_persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['human_persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_sessions_ai_persona_id'), 'persona_sessions', ['ai_persona_id'], unique=False)
    op.create_index(op.f('ix_persona_sessions_human_persona_id'), 'persona_sessions', ['human_persona_id'], unique=False)
    op.create_index(op.f('ix_persona_sessions_id'), 'persona_sessions', ['id'], unique=False)
    op.add_column('messages', sa.Column('persona_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_persona_session_id'), 'messages', ['persona_session_id'], unique=False)
    op.create_foreign_key(
        'fk_messages_persona_session_id_persona_sessions',
        'messages', 'persona_sessions', ['persona_session_id'], ['id']
    )
    # ### end Alembic commands ###

    # --- Data backfill: traits.brain / traits.interests_expertise.expertise ---
    # Pulled from the hardcoded active_persona singleton in
    # app/persona/persona_session.py (being retired in this same body of
    # work) so behavior doesn't silently reset to defaults for the Trump
    # persona. Every other existing persona with non-null traits gets
    # explicit 50.0-across-the-board brain defaults written in, rather than
    # left null, per product decision.
    personas_table = table(
        'personas',
        column('id', sa.Integer),
        column('name', sa.String),
        column('traits', JSONB),
    )

    TRUMP_BRAIN = {
        "threat_sensitivity": 30.0,
        "self_regulation": 80.0,
        "novelty_drive": 55.0,
        "baseline_security": 80.0,
        "empathic_resonance": 25.0,
    }
    TRUMP_EXPERTISE = [
        "domestic and international politics, geopolitics",
        "the persona's own life, career, and personal history",
        "real estate, business deals, and investments",
    ]
    DEFAULT_BRAIN = {
        "threat_sensitivity": 50.0,
        "self_regulation": 50.0,
        "novelty_drive": 50.0,
        "baseline_security": 50.0,
        "empathic_resonance": 50.0,
    }

    conn = op.get_bind()
    rows = conn.execute(
        sa.select(personas_table.c.id, personas_table.c.name, personas_table.c.traits)
    ).fetchall()

    for row in rows:
        traits = row.traits
        if traits is None:
            continue
        if isinstance(traits, str):
            try:
                traits = json.loads(traits)
            except (ValueError, TypeError):
                continue
        if not isinstance(traits, dict):
            continue

        if row.name == "Donald Trump":
            traits["brain"] = dict(TRUMP_BRAIN)
            traits.setdefault("interests_expertise", {})
            traits["interests_expertise"]["expertise"] = list(TRUMP_EXPERTISE)
        elif not traits.get("brain"):
            traits["brain"] = dict(DEFAULT_BRAIN)
        else:
            continue  # already has explicit brain values, leave as-is

        conn.execute(
            personas_table.update()
            .where(personas_table.c.id == row.id)
            .values(traits=traits)
        )


def downgrade() -> None:
    """Downgrade schema.

    Note: the traits.brain / traits.interests_expertise.expertise data
    backfill in upgrade() is not reversed here — it's an additive change to
    existing JSON, not a schema change, and safe to leave in place.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_persona_session_id_persona_sessions', 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_persona_session_id'), table_name='messages')
    op.drop_column('messages', 'persona_session_id')
    op.drop_index(op.f('ix_persona_sessions_id'), table_name='persona_sessions')
    op.drop_index(op.f('ix_persona_sessions_human_persona_id'), table_name='persona_sessions')
    op.drop_index(op.f('ix_persona_sessions_ai_persona_id'), table_name='persona_sessions')
    op.drop_table('persona_sessions')
    # ### end Alembic commands ###
